# Generated by Django 3.2.9 on 2023-08-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Muallifning ismini kiriting', max_length=100, verbose_name='Muallifning ismi')),
                ('last_name', models.CharField(help_text='Muallifning familiyasini kiriting', max_length=100, verbose_name='Muallifning familiyasi')),
                ('date_of_birth', models.DateField(blank=True, help_text="Tug'ilgan sanasini kiriting", null=True, verbose_name="Tug'ilgan sanasi")),
                ('date_of_death', models.DateField(blank=True, help_text="O'lgan sanasini kiriting", null=True, verbose_name="O'lim sanasi")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kitobning nomini kiriting', max_length=200, verbose_name='Kitobning nomi')),
                ('summary', models.CharField(help_text="Kitob uchun qisqa ta'rif yozing", max_length=100, verbose_name='Kitob annotatsiyasi')),
                ('isbn', models.CharField(help_text="13 belgidan iborat bo'lishi shart", max_length=13, verbose_name='Kitobning ISBN')),
                ('author', models.ManyToManyField(help_text='Kitobnign muallifini kiriting', to='catalog.Author', verbose_name='Kitob muallifi')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitobning janrini kiriting', max_length=200, verbose_name='Kitobning janri')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitobning tilini kiriting', max_length=200, verbose_name='Kitobning tili')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitobning nusxasini kiriting', max_length=20, verbose_name='Kitob nusxasining holati')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Kitob nusxasining inventariy nomerini kiriting', max_length=20, null=True, verbose_name='Inventariy nomer')),
                ('imprint', models.CharField(help_text='Nashriyotni hamda ishlab chiqarilgan yilni kiriting', max_length=200, verbose_name='Nashriyot')),
                ('due_back', models.DateField(blank=True, help_text='Holatning muddatining sanasini kiriting', null=True, verbose_name='Holat tugashining muddat sanasi')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text="Kitob nusxasini holatini o'zgartirish", null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Kitob nusxasining holati')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Kitob uchun janr tanlang', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Kitob janri'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Kitob uchun til tanlang', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Kitob tili'),
        ),
    ]
