# Generated by Django 3.2.9 on 2023-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(help_text="Kitob uchun qisqa ta'rif yozing", max_length=1000, verbose_name='Kitob annotatsiyasi'),
        ),
    ]
